// <auto-generated />
using System;
using ClanGuardBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanGuardBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260725202658_AddSatisfactoryMetricSamples")]
    partial class AddSatisfactoryMetricSamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClanGuardBot.Models.AccountAgeGateExemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddedByUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("AccountAgeGateExemptions");
                });

            modelBuilder.Entity("ClanGuardBot.Models.ApolloEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParsedEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ParsedOrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedOrganizerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParsedStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId")
                        .IsUnique();

                    b.HasIndex("GuildId", "Status", "ParsedStartUtc");

                    b.ToTable("ApolloEvents", (string)null);
                });

            modelBuilder.Entity("ClanGuardBot.Models.ApolloMessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParseError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("DiscordMessageId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex("ProcessedAt", "CapturedAt");

                    b.ToTable("ApolloMessageLog", (string)null);
                });

            modelBuilder.Entity("ClanGuardBot.Models.AwolKickAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("InvokerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvokerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesAtKick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasDryRun")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ProcessedAt");

                    b.HasIndex("InvokerId", "ProcessedAt");

                    b.HasIndex("GuildId", "UserId", "ProcessedAt");

                    b.ToTable("AwolKickAudits");
                });

            modelBuilder.Entity("ClanGuardBot.Models.AwolRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNotificationAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("NotificationChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("NotificationMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId");

                    b.HasIndex("NotificationSent", "AssignedAt");

                    b.ToTable("AwolRecords");
                });

            modelBuilder.Entity("ClanGuardBot.Models.BotState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanHammerLastBanReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanHammerLastBanTarget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BanHammerLastBanUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("BanHammerMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanHammerRecordDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BanHammerSeededFromHistory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanHammerTotalBans")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("GamertagButtonMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoneypotBanCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("HoneypotWarningMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAutoPromotionCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBriefingCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDiscordStatusPollCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDiscordStatusPollError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRosterExportCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSqliteBackupCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSqliteBackupError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSqliteBackupSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastWebhookAuditScanCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("OfficerAppButtonMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TicketPanelMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BotStates");
                });

            modelBuilder.Entity("ClanGuardBot.Models.BumpState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastBumpAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReminderAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("BumpStates");
                });

            modelBuilder.Entity("ClanGuardBot.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteOnCancelTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMeetingSnapshotAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSnapshotAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PendingCancelUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_CalendarEvents_DiscordMessageId_Unique")
                        .HasFilter("\"DiscordMessageId\" <> 0");

                    b.HasIndex("PendingCancelUntil")
                        .HasDatabaseName("IX_CalendarEvents_PendingCancelUntil");

                    b.HasIndex("GuildId", "ContentHash")
                        .HasDatabaseName("IX_CalendarEvents_GuildId_ContentHash");

                    b.HasIndex("GuildId", "Source");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("ClanGuardBot.Models.CalendarOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalendarEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.HasIndex("CompletedAt", "NextAttemptAt")
                        .HasDatabaseName("IX_CalendarOutbox_Pending");

                    b.ToTable("CalendarOutbox");
                });

            modelBuilder.Entity("ClanGuardBot.Models.ClanEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalendarEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LastReminderMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemindersSentCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClanEvents_MessageId_Unique")
                        .HasFilter("\"MessageId\" <> 0");

                    b.HasIndex("GuildId", "StartUtc");

                    b.HasIndex("SeriesId", "StartUtc")
                        .IsUnique();

                    b.HasIndex("Status", "StartUtc");

                    b.ToTable("ClanEvents");
                });

            modelBuilder.Entity("ClanGuardBot.Models.ClanEventSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstStartLocal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UntilUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Active");

                    b.ToTable("ClanEventSeries");
                });

            modelBuilder.Entity("ClanGuardBot.Models.ClanEventTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ClanEventTemplates");
                });

            modelBuilder.Entity("ClanGuardBot.Models.ClanReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AnnouncementMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstFireLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextFireUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextOccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingEveryone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingHere")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PingRoleIdsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PingUserIdsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.HasIndex("Status", "NextFireUtc");

                    b.ToTable("ClanReminders");
                });

            modelBuilder.Entity("ClanGuardBot.Models.CommandUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubcommandPath")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("GuildId", "CommandName", "ExecutedAt");

                    b.HasIndex("GuildId", "UserId", "ExecutedAt");

                    b.ToTable("CommandUsages");
                });

            modelBuilder.Entity("ClanGuardBot.Models.DiscordStatusIncidentUpdate", b =>
                {
                    b.Property<string>("UpdateId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("UpdateId");

                    b.HasIndex("IncidentId");

                    b.ToTable("DiscordStatusIncidentUpdates");
                });

            modelBuilder.Entity("ClanGuardBot.Models.EventAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalendarEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.HasIndex("GuildId", "UserId", "CalendarEventId")
                        .IsUnique();

                    b.HasIndex("GuildId", "UserId", "EventEndUtc");

                    b.ToTable("EventAttendances");
                });

            modelBuilder.Entity("ClanGuardBot.Models.EventRsvp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanEventId");

                    b.HasIndex("ClanEventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventRsvps");
                });

            modelBuilder.Entity("ClanGuardBot.Models.GuestReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReminderAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("GuestReminders");
                });

            modelBuilder.Entity("ClanGuardBot.Models.InviteJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("InviterDiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAmbiguous")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserDiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDiscordId");

                    b.HasIndex("GuildId", "InviteCode");

                    b.HasIndex("GuildId", "JoinedAt");

                    b.ToTable("InviteJoins");
                });

            modelBuilder.Entity("ClanGuardBot.Models.InviteSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("CreatedByDiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DiscordCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVanity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByDiscordId");

                    b.HasIndex("GuildId", "Code")
                        .IsUnique();

                    b.HasIndex("GuildId", "IsActive");

                    b.ToTable("InviteSources");
                });

            modelBuilder.Entity("ClanGuardBot.Models.KnownMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoinedAtCached")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankCached")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesCached")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("KnownMembers");
                });

            modelBuilder.Entity("ClanGuardBot.Models.MeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalendarEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventId");

                    b.HasIndex("GuildId", "UserId", "CalendarEventId")
                        .IsUnique();

                    b.HasIndex("GuildId", "UserId", "EventEndUtc");

                    b.ToTable("MeetingAttendances");
                });

            modelBuilder.Entity("ClanGuardBot.Models.MeetingRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionItemsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioDirPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("CalendarEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetingEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetingStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("MinutesMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinutesText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecordingStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecordingStoppedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StateUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMessageId");

                    b.HasIndex("State");

                    b.ToTable("MeetingRecordings");
                });

            modelBuilder.Entity("ClanGuardBot.Models.MemberDeparture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDetection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsAttendedLifetime")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HadReserve")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRejoin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinSourceLabel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinedAtSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesLifetime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankAtDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesAtDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TenureDays")
                        .HasColumnType("REAL");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasGuest")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DepartedAt");

                    b.HasIndex("GuildId", "Classification", "DepartedAt");

                    b.HasIndex("GuildId", "UserId", "DepartedAt");

                    b.ToTable("MemberDepartures");
                });

            modelBuilder.Entity("ClanGuardBot.Models.MessageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "Timestamp");

                    b.ToTable("MessageEvents");
                });

            modelBuilder.Entity("ClanGuardBot.Models.OfficerApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DossierMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q1AreaOfInterest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Q2Ideas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Q3Conflict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ReviewedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewedByUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "Status");

                    b.ToTable("OfficerApplications");
                });

            modelBuilder.Entity("ClanGuardBot.Models.OnboardingReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("OnboardingReminders");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PalworldLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LinkedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PalworldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalworldUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique();

                    b.HasIndex("GuildId", "PalworldUserId")
                        .IsUnique();

                    b.ToTable("PalworldLinks");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PalworldMetricSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCampCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FrameTimeMs")
                        .HasColumnType("REAL");

                    b.Property<int>("InGameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SampledUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerFps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SampledUtc");

                    b.ToTable("PalworldMetricSamples");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PalworldNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalworldUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SetByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PalworldUserId")
                        .IsUnique();

                    b.ToTable("PalworldNameOverrides");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PalworldSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildingCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PalworldPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalworldUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndedUtc")
                        .HasFilter("\"EndedUtc\" IS NULL");

                    b.HasIndex("PlayerName");

                    b.HasIndex("PalworldUserId", "StartedUtc");

                    b.ToTable("PalworldSessions");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PatrolWatchNameOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SetByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("PatrolWatchNameOverrides");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PatrolWatchOptOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OptedOutAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("PatrolWatchOptOuts");
                });

            modelBuilder.Entity("ClanGuardBot.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowMultiselect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnnounceOnClose")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosesAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemindAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ResultsAnnounced")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ResultsMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("GuildId", "CreatedAt");

                    b.HasIndex("Status", "ClosesAtUtc");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PollId", "AnswerId");

                    b.HasIndex("PollId", "Position")
                        .IsUnique();

                    b.ToTable("PollOptions");
                });

            modelBuilder.Entity("ClanGuardBot.Models.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PollId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex("PollId", "UserId");

                    b.HasIndex("PollId", "UserId", "PollOptionId")
                        .IsUnique();

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("ClanGuardBot.Models.RankChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromRank")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToRank")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ChangedAt");

                    b.HasIndex("GuildId", "UserId", "ChangedAt");

                    b.ToTable("RankChanges");
                });

            modelBuilder.Entity("ClanGuardBot.Models.RankHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsAttendedAtRankBeforeBot")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SeedAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("RankHistories");
                });

            modelBuilder.Entity("ClanGuardBot.Models.RedditLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorAccountAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorKarma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ClaimedByDiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimedByUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContactedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OutcomeAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedditPostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subreddit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredAtUtc");

                    b.HasIndex("RedditPostId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Subreddit");

                    b.ToTable("RedditLeads");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SatisfactoryDailySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CircuitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedDays")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PowerCapacityMw")
                        .HasColumnType("REAL");

                    b.Property<double?>("PowerConsumedMw")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProducingItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SinkCoupons")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SinkTotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TakenUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalProductionPerMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Seed", "LocalDate")
                        .IsUnique();

                    b.HasIndex("Seed", "TakenUtc");

                    b.ToTable("SatisfactoryDailySnapshots");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SatisfactoryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LinkedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SatisfactoryPlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique();

                    b.HasIndex("GuildId", "SatisfactoryPlayerName")
                        .IsUnique();

                    b.ToTable("SatisfactoryLinks");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SatisfactoryMetricSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BatteryPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("CircuitCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PowerCapacityMw")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerConsumedMw")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerProductionMw")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SampledUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrippedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SampledUtc");

                    b.ToTable("SatisfactoryMetricSamples");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SatisfactorySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndedUtc")
                        .HasFilter("\"EndedUtc\" IS NULL");

                    b.HasIndex("PlayerName", "StartedUtc");

                    b.ToTable("SatisfactorySessions");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SatisfactoryUnlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnlockId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Seed", "Kind");

                    b.HasIndex("Seed", "Kind", "UnlockId")
                        .IsUnique();

                    b.ToTable("SatisfactoryUnlocks");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SecurityAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "OccurredAt");

                    b.HasIndex("GuildId", "Feature", "OccurredAt");

                    b.HasIndex("GuildId", "UserId", "OccurredAt")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("SecurityAuditRecords");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnonHandle")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ClaimedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimedByUsername")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("ClosedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedByUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ControlMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeaveScheduled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LeaveStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenerDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OpenerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReserveAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RoutedRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ControlMessageId");

                    b.HasIndex("LeaveScheduled");

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.HasIndex("GuildId", "OpenerUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_SupportTickets_OneOpenAnonPerUser")
                        .HasFilter("\"IsAnonymous\" = 1 AND \"Status\" <> 3");

                    b.HasIndex("GuildId", "OpenerUserId", "Status");

                    b.HasIndex("GuildId", "Status", "LastActivityUtc");

                    b.HasIndex("Status", "ReserveAssigned", "LeaveEndUtc");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("ClanGuardBot.Models.SupportTicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AuthorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "SentUtc");

                    b.ToTable("SupportTicketMessages");
                });

            modelBuilder.Entity("ClanGuardBot.Models.TicketReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("TicketReminders");
                });

            modelBuilder.Entity("ClanGuardBot.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoiceJoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WindowResetAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("ClanGuardBot.Models.UserTimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IanaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTimeZones");
                });

            modelBuilder.Entity("ClanGuardBot.Models.VoiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "ChannelId");

                    b.HasIndex("GuildId", "UserId", "JoinedAt");

                    b.ToTable("VoiceSessions");
                });

            modelBuilder.Entity("ClanGuardBot.Models.WebhookSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CreatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("WebhookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ChannelId");

                    b.HasIndex("GuildId", "WebhookId")
                        .IsUnique();

                    b.ToTable("WebhookSnapshots");
                });

            modelBuilder.Entity("ClanGuardBot.Models.XpAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "SeasonId", "UserId");

                    b.HasIndex("GuildId", "UserId", "Source", "SourceKey")
                        .IsUnique();

                    b.ToTable("XpAwards");
                });

            modelBuilder.Entity("ClanGuardBot.Models.XpDmOptOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OptedOutAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("XpDmOptOuts");
                });

            modelBuilder.Entity("ClanGuardBot.Models.XpMemberSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastAnnouncedLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastEarnedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "SeasonId", "UserId")
                        .IsUnique();

                    b.HasIndex("GuildId", "SeasonId", "Xp");

                    b.ToTable("XpMemberSeasons");
                });

            modelBuilder.Entity("ClanGuardBot.Models.XpMemberTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AllTimeXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestSeasonPlace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestSeasonXp")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonsPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("XpMemberTotals");
                });

            modelBuilder.Entity("ClanGuardBot.Models.XpSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Number")
                        .IsUnique();

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("XpSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
